apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: flavio-e2e
  janus-idp.io/tekton: flavio-e2e
  backstage.io/kubernetes-id: flavio-e2e
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: flavio-e2e
resources: 
- deployment.yaml
- route.yaml
- service.yaml
