apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: flavio-e2e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flavio-e2e 
  name: flavio-e2e
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: flavio-e2e
    weight: 100 
